import { Flex } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import { Footer } from "../components/Footer/Footer";
import { Header } from "../components/Header/Header";
import { NavBar } from "../components/NavBar/NavBar";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Chainwhiz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Flex direction={"column"} justifyContent={"space-between"}>
        <NavBar />
        <hr className={styles.divider} />
        <Header />
        <hr className={styles.divider} />
        <Footer />
      </Flex>
    </div>
  );
};

export default Home;
